### PR TITLE
Depend on the Homebrew installed OpenSSL library

### PR DESCRIPTION
**Pull request by orien**
OS X 10.11 El Capitan does not include OpenSSL headers. To support this Mac version we need to depend on the Homebrew-installed OpenSSL library.

### CODE REVIEW

**Comment by habitullence** [comment]
Good job @orien :)

**Comment by orien** [comment]
FYI: to try this in your `our-boxen`, update your Puppetfile:
```diff
-github "nginx", "1.4.6"
+github "nginx", "0.0.0", :repo => "orien/puppet-nginx"
```

**Comment by karlbright** [comment]
:+1: after using @orien's branch within my boxen setup without issues.

**Comment by grosser** [comment]
@tarebyte / @dgoodlad / @fromonesrc

**Comment by pearpair** [comment]
@mikemcquaid @tarebyte Yo can we get this merged in ASAP?

**Comment by seanknox** [comment]
Thanks @orien!

**Pull request merged**
