### PR TITLE
bump nginx

### PR DESCRIPTION
**Pull request by grosser**
@isaacsu @tarebyte

### CODE REVIEW

**Comment by orien** [comment]
We'll need to ensure the new version is installed also.
https://github.com/boxen/puppet-nginx/blob/master/manifests/init.pp#L58

**Comment by grosser** [comment]
done! Good to go ?

**Comment by isaacsu** [comment]
:+1:

**Comment by orien** [comment]
+1

**Comment by grosser** [comment]
@tarebyte / @dgoodlad  / @fromonesrc merge ?

**Comment by grosser** [comment]
maybe @rafaelfranca since you have access to all repos in the world ? ;)

**Comment by rafaelfranca** [comment]
Released as 1.5.0 https://github.com/boxen/puppet-nginx/releases/tag/1.5.0

**Comment by grosser** [comment]
woah that was quick, thx :D

**Comment by rafaelfranca** [comment]
BTW, let me add you to the team since you are using boxen in your org.

**Comment by grosser** [comment]
thx! :)

**Pull request merged**
